//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 01:43:44 PM CEST 
//


package rs.ac.uns.ftn.model.dto.presek;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import rs.ac.uns.ftn.model.dto.presek.stavkapreseka.StavkaPreseka;
import rs.ac.uns.ftn.model.dto.presek.zaglavljepreseka.ZaglavljePreseka;


/**
 * <p>Java class for presek complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="presek"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zaglavljePreseka}zaglavlje_preseka"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/stavkaPreseka}stavka_preseka" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "presek", propOrder = {
    "zaglavljePreseka",
    "stavkaPreseka"
})
public class Presek {

    @XmlElement(name = "zaglavlje_preseka", namespace = "http://www.ftn.uns.ac.rs/zaglavljePreseka", required = true)
    protected ZaglavljePreseka zaglavljePreseka;
    @XmlElement(name = "stavka_preseka", namespace = "http://www.ftn.uns.ac.rs/stavkaPreseka", required = true)
    protected List<StavkaPreseka> stavkaPreseka;

    /**
     * Gets the value of the zaglavljePreseka property.
     * 
     * @return
     *     possible object is
     *     {@link ZaglavljePreseka }
     *     
     */
    public ZaglavljePreseka getZaglavljePreseka() {
        return zaglavljePreseka;
    }

    /**
     * Sets the value of the zaglavljePreseka property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZaglavljePreseka }
     *     
     */
    public void setZaglavljePreseka(ZaglavljePreseka value) {
        this.zaglavljePreseka = value;
    }

    /**
     * Gets the value of the stavkaPreseka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavkaPreseka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavkaPreseka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StavkaPreseka }
     * 
     * 
     */
    public List<StavkaPreseka> getStavkaPreseka() {
        if (stavkaPreseka == null) {
            stavkaPreseka = new ArrayList<StavkaPreseka>();
        }
        return this.stavkaPreseka;
    }

    /**
     * Sets the value of the stavkaPreseka property.
     *
     * @param value
     *     allowed object is
     *     {@link List<StavkaPreseka> }
     *
     */
    public void setStavkaPreseka(List<StavkaPreseka> value) {
        this.stavkaPreseka = value;
    }



}
