//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 02:14:19 PM CEST 
//


package rs.ac.uns.ftn.model.dto.mt102;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import rs.ac.uns.ftn.model.dto.mt102body.Mt102Telo;
import rs.ac.uns.ftn.model.dto.mt102header.Mt102Zaglavlje;


/**
 * <p>Java class for mt102 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mt102"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/mt102header}mt102_zaglavlje"/&gt;
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/mt102body}mt102_telo" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mt102", propOrder = {
    "mt102Zaglavlje",
    "mt102Telo"
})
public class Mt102 {

    @XmlElement(name = "mt102_zaglavlje", namespace = "http://www.ftn.uns.ac.rs/mt102header", required = true)
    protected Mt102Zaglavlje mt102Zaglavlje;
    @XmlElement(name = "mt102_telo", namespace = "http://www.ftn.uns.ac.rs/mt102body", required = true)
    protected List<Mt102Telo> mt102Telo;

    /**
     * Gets the value of the mt102Zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link Mt102Zaglavlje }
     *     
     */
    public Mt102Zaglavlje getMt102Zaglavlje() {
        return mt102Zaglavlje;
    }

    /**
     * Sets the value of the mt102Zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mt102Zaglavlje }
     *     
     */
    public void setMt102Zaglavlje(Mt102Zaglavlje value) {
        this.mt102Zaglavlje = value;
    }

    /**
     * Gets the value of the mt102Telo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mt102Telo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMt102Telo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mt102Telo }
     * 
     * 
     */
    public List<Mt102Telo> getMt102Telo() {
        if (mt102Telo == null) {
            mt102Telo = new ArrayList<Mt102Telo>();
        }
        return this.mt102Telo;
    }

}
