//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 02:57:08 PM CEST 
//


package com.ftn.model.dto.mt102.mt102header;

import com.ftn.model.dto.types.TOznakaValute;
import com.ftn.model.dto.types.TPodaciBanka;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podaci_o_banci_duznika" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciBanka"/&gt;
 *         &lt;element name="podaci_o_banci_poverioca" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciBanka"/&gt;
 *         &lt;element name="ukupan_iznos"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;totalDigits value="15"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datum_valute" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="sifra_valute" type="{http://www.ftn.uns.ac.rs/tipovi}TOznakaValute"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id_poruke"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOBanciDuznika",
    "podaciOBanciPoverioca",
    "ukupanIznos",
    "datumValute",
    "datum",
    "sifraValute"
})
@XmlRootElement(name = "mt102_zaglavlje")
public class Mt102Zaglavlje {

    @XmlElement(name = "podaci_o_banci_duznika", required = true)
    protected TPodaciBanka podaciOBanciDuznika;
    @XmlElement(name = "podaci_o_banci_poverioca", required = true)
    protected TPodaciBanka podaciOBanciPoverioca;
    @XmlElement(name = "ukupan_iznos", required = true)
    protected BigDecimal ukupanIznos;
    @XmlElement(name = "datum_valute", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumValute;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(name = "sifra_valute", required = true)
    @XmlSchemaType(name = "string")
    protected TOznakaValute sifraValute;
    @XmlAttribute(name = "id_poruke")
    protected String idPoruke;

    /**
     * Gets the value of the podaciOBanciDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link TPodaciBanka }
     *     
     */
    public TPodaciBanka getPodaciOBanciDuznika() {
        return podaciOBanciDuznika;
    }

    /**
     * Sets the value of the podaciOBanciDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPodaciBanka }
     *     
     */
    public void setPodaciOBanciDuznika(TPodaciBanka value) {
        this.podaciOBanciDuznika = value;
    }

    /**
     * Gets the value of the podaciOBanciPoverioca property.
     * 
     * @return
     *     possible object is
     *     {@link TPodaciBanka }
     *     
     */
    public TPodaciBanka getPodaciOBanciPoverioca() {
        return podaciOBanciPoverioca;
    }

    /**
     * Sets the value of the podaciOBanciPoverioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPodaciBanka }
     *     
     */
    public void setPodaciOBanciPoverioca(TPodaciBanka value) {
        this.podaciOBanciPoverioca = value;
    }

    /**
     * Gets the value of the ukupanIznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanIznos() {
        return ukupanIznos;
    }

    /**
     * Sets the value of the ukupanIznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanIznos(BigDecimal value) {
        this.ukupanIznos = value;
    }

    /**
     * Gets the value of the datumValute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumValute() {
        return datumValute;
    }

    /**
     * Sets the value of the datumValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumValute(XMLGregorianCalendar value) {
        this.datumValute = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the sifraValute property.
     * 
     * @return
     *     possible object is
     *     {@link TOznakaValute }
     *     
     */
    public TOznakaValute getSifraValute() {
        return sifraValute;
    }

    /**
     * Sets the value of the sifraValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOznakaValute }
     *     
     */
    public void setSifraValute(TOznakaValute value) {
        this.sifraValute = value;
    }

    /**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPoruke(String value) {
        this.idPoruke = value;
    }

}
