//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 01:16:53 PM CEST 
//


package rs.ac.uns.ftn.model.dto.zahtev_za_izvod;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zahtev_za_izvod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zahtevZaIzvod"
})
@XmlRootElement(name = "getZahtevZaIzvodResponse")
public class GetZahtevZaIzvodResponse {

    @XmlElement(name = "zahtev_za_izvod", required = true)
    protected String zahtevZaIzvod;

    /**
     * Gets the value of the zahtevZaIzvod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevZaIzvod() {
        return zahtevZaIzvod;
    }

    /**
     * Sets the value of the zahtevZaIzvod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevZaIzvod(String value) {
        this.zahtevZaIzvod = value;
    }

}
