//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 01:52:57 PM CEST 
//


package rs.ac.uns.ftn.model.dto.mt103;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import rs.ac.uns.ftn.model.dto.tipovi.TPodaciBanka;
import rs.ac.uns.ftn.model.dto.tipovi.TPodaciPlacanje;
import rs.ac.uns.ftn.model.dto.tipovi.TPravnoLice;


/**
 * <p>Java class for mt103 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mt103"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podaci_o_duzniku"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.ftn.uns.ac.rs/tipovi}TPravnoLice"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="podaci_o_banci" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciBanka"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podaci_o_poveriocu"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://www.ftn.uns.ac.rs/tipovi}TPravnoLice"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="podaci_o_banci" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciBanka"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podaci_o_uplati"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="svrha_placanja"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;maxLength value="255"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="iznos"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.ftn.uns.ac.rs/tipovi&gt;TIznos"&gt;
 *                           &lt;attribute name="valuta"&gt;
 *                             &lt;simpleType&gt;
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                 &lt;enumeration value="RSD"/&gt;
 *                                 &lt;enumeration value="USD"/&gt;
 *                                 &lt;enumeration value="EUR"/&gt;
 *                               &lt;/restriction&gt;
 *                             &lt;/simpleType&gt;
 *                           &lt;/attribute&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="podaci_o_zaduzenju" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciPlacanje"/&gt;
 *                   &lt;element name="podaci_o_odobrenju" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciPlacanje"/&gt;
 *                   &lt;element name="datum_naloga" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="datum_valute" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id_poruke"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;maxLength value="50"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mt103", propOrder = {
    "podaciODuzniku",
    "podaciOPoveriocu",
    "podaciOUplati"
})
public class Mt103 {

    @XmlElement(name = "podaci_o_duzniku", required = true)
    protected PodaciODuzniku podaciODuzniku;
    @XmlElement(name = "podaci_o_poveriocu", required = true)
    protected PodaciOPoveriocu podaciOPoveriocu;
    @XmlElement(name = "podaci_o_uplati", required = true)
    protected PodaciOUplati podaciOUplati;
    @XmlAttribute(name = "id_poruke")
    protected String idPoruke;

    /**
     * Gets the value of the podaciODuzniku property.
     * 
     * @return
     *     possible object is
     *     {@link Mt103 .PodaciODuzniku }
     *     
     */
    public PodaciODuzniku getPodaciODuzniku() {
        return podaciODuzniku;
    }

    /**
     * Sets the value of the podaciODuzniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mt103 .PodaciODuzniku }
     *     
     */
    public void setPodaciODuzniku(PodaciODuzniku value) {
        this.podaciODuzniku = value;
    }

    /**
     * Gets the value of the podaciOPoveriocu property.
     * 
     * @return
     *     possible object is
     *     {@link Mt103 .PodaciOPoveriocu }
     *     
     */
    public PodaciOPoveriocu getPodaciOPoveriocu() {
        return podaciOPoveriocu;
    }

    /**
     * Sets the value of the podaciOPoveriocu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mt103 .PodaciOPoveriocu }
     *     
     */
    public void setPodaciOPoveriocu(PodaciOPoveriocu value) {
        this.podaciOPoveriocu = value;
    }

    /**
     * Gets the value of the podaciOUplati property.
     * 
     * @return
     *     possible object is
     *     {@link Mt103 .PodaciOUplati }
     *     
     */
    public PodaciOUplati getPodaciOUplati() {
        return podaciOUplati;
    }

    /**
     * Sets the value of the podaciOUplati property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mt103 .PodaciOUplati }
     *     
     */
    public void setPodaciOUplati(PodaciOUplati value) {
        this.podaciOUplati = value;
    }

    /**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPoruke(String value) {
        this.idPoruke = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.ftn.uns.ac.rs/tipovi}TPravnoLice"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="podaci_o_banci" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciBanka"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podaciOBanci"
    })
    public static class PodaciODuzniku
        extends TPravnoLice
    {

        @XmlElement(name = "podaci_o_banci", required = true)
        protected TPodaciBanka podaciOBanci;

        /**
         * Gets the value of the podaciOBanci property.
         * 
         * @return
         *     possible object is
         *     {@link TPodaciBanka }
         *     
         */
        public TPodaciBanka getPodaciOBanci() {
            return podaciOBanci;
        }

        /**
         * Sets the value of the podaciOBanci property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPodaciBanka }
         *     
         */
        public void setPodaciOBanci(TPodaciBanka value) {
            this.podaciOBanci = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://www.ftn.uns.ac.rs/tipovi}TPravnoLice"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="podaci_o_banci" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciBanka"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podaciOBanci"
    })
    public static class PodaciOPoveriocu
        extends TPravnoLice
    {

        @XmlElement(name = "podaci_o_banci", required = true)
        protected TPodaciBanka podaciOBanci;

        /**
         * Gets the value of the podaciOBanci property.
         * 
         * @return
         *     possible object is
         *     {@link TPodaciBanka }
         *     
         */
        public TPodaciBanka getPodaciOBanci() {
            return podaciOBanci;
        }

        /**
         * Sets the value of the podaciOBanci property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPodaciBanka }
         *     
         */
        public void setPodaciOBanci(TPodaciBanka value) {
            this.podaciOBanci = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="svrha_placanja"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;maxLength value="255"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="iznos"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.ftn.uns.ac.rs/tipovi&gt;TIznos"&gt;
     *                 &lt;attribute name="valuta"&gt;
     *                   &lt;simpleType&gt;
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                       &lt;enumeration value="RSD"/&gt;
     *                       &lt;enumeration value="USD"/&gt;
     *                       &lt;enumeration value="EUR"/&gt;
     *                     &lt;/restriction&gt;
     *                   &lt;/simpleType&gt;
     *                 &lt;/attribute&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="podaci_o_zaduzenju" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciPlacanje"/&gt;
     *         &lt;element name="podaci_o_odobrenju" type="{http://www.ftn.uns.ac.rs/tipovi}TPodaciPlacanje"/&gt;
     *         &lt;element name="datum_naloga" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="datum_valute" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "svrhaPlacanja",
        "iznos",
        "podaciOZaduzenju",
        "podaciOOdobrenju",
        "datumNaloga",
        "datumValute"
    })
    public static class PodaciOUplati {

        @XmlElement(name = "svrha_placanja", required = true)
        protected String svrhaPlacanja;
        @XmlElement(required = true)
        protected Iznos iznos;
        @XmlElement(name = "podaci_o_zaduzenju", required = true)
        protected TPodaciPlacanje podaciOZaduzenju;
        @XmlElement(name = "podaci_o_odobrenju", required = true)
        protected TPodaciPlacanje podaciOOdobrenju;
        @XmlElement(name = "datum_naloga", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumNaloga;
        @XmlElement(name = "datum_valute", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumValute;

        /**
         * Gets the value of the svrhaPlacanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSvrhaPlacanja() {
            return svrhaPlacanja;
        }

        /**
         * Sets the value of the svrhaPlacanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSvrhaPlacanja(String value) {
            this.svrhaPlacanja = value;
        }

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link Mt103 .PodaciOUplati.Iznos }
         *     
         */
        public Iznos getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mt103 .PodaciOUplati.Iznos }
         *     
         */
        public void setIznos(Iznos value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the podaciOZaduzenju property.
         * 
         * @return
         *     possible object is
         *     {@link TPodaciPlacanje }
         *     
         */
        public TPodaciPlacanje getPodaciOZaduzenju() {
            return podaciOZaduzenju;
        }

        /**
         * Sets the value of the podaciOZaduzenju property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPodaciPlacanje }
         *     
         */
        public void setPodaciOZaduzenju(TPodaciPlacanje value) {
            this.podaciOZaduzenju = value;
        }

        /**
         * Gets the value of the podaciOOdobrenju property.
         * 
         * @return
         *     possible object is
         *     {@link TPodaciPlacanje }
         *     
         */
        public TPodaciPlacanje getPodaciOOdobrenju() {
            return podaciOOdobrenju;
        }

        /**
         * Sets the value of the podaciOOdobrenju property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPodaciPlacanje }
         *     
         */
        public void setPodaciOOdobrenju(TPodaciPlacanje value) {
            this.podaciOOdobrenju = value;
        }

        /**
         * Gets the value of the datumNaloga property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumNaloga() {
            return datumNaloga;
        }

        /**
         * Sets the value of the datumNaloga property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumNaloga(XMLGregorianCalendar value) {
            this.datumNaloga = value;
        }

        /**
         * Gets the value of the datumValute property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumValute() {
            return datumValute;
        }

        /**
         * Sets the value of the datumValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumValute(XMLGregorianCalendar value) {
            this.datumValute = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.ftn.uns.ac.rs/tipovi&gt;TIznos"&gt;
         *       &lt;attribute name="valuta"&gt;
         *         &lt;simpleType&gt;
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *             &lt;enumeration value="RSD"/&gt;
         *             &lt;enumeration value="USD"/&gt;
         *             &lt;enumeration value="EUR"/&gt;
         *           &lt;/restriction&gt;
         *         &lt;/simpleType&gt;
         *       &lt;/attribute&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Iznos {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "valuta")
            protected String valuta;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the valuta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValuta() {
                return valuta;
            }

            /**
             * Sets the value of the valuta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValuta(String value) {
                this.valuta = value;
            }

        }

    }

}
