//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 01:52:57 PM CEST 
//


package rs.ac.uns.ftn.model.dto.mt103;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.model.dto.mt103 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.model.dto.mt103
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mt103 }
     * 
     */
    public Mt103 createMt103() {
        return new Mt103();
    }

    /**
     * Create an instance of {@link Mt103 .PodaciOUplati }
     * 
     */
    public Mt103 .PodaciOUplati createMt103PodaciOUplati() {
        return new Mt103 .PodaciOUplati();
    }

    /**
     * Create an instance of {@link GetMt103Request }
     * 
     */
    public GetMt103Request createGetMt103Request() {
        return new GetMt103Request();
    }

    /**
     * Create an instance of {@link GetMt103Response }
     * 
     */
    public GetMt103Response createGetMt103Response() {
        return new GetMt103Response();
    }

    /**
     * Create an instance of {@link Mt103 .PodaciODuzniku }
     * 
     */
    public Mt103 .PodaciODuzniku createMt103PodaciODuzniku() {
        return new Mt103 .PodaciODuzniku();
    }

    /**
     * Create an instance of {@link Mt103 .PodaciOPoveriocu }
     * 
     */
    public Mt103 .PodaciOPoveriocu createMt103PodaciOPoveriocu() {
        return new Mt103 .PodaciOPoveriocu();
    }

    /**
     * Create an instance of {@link Mt103 .PodaciOUplati.Iznos }
     * 
     */
    public Mt103 .PodaciOUplati.Iznos createMt103PodaciOUplatiIznos() {
        return new Mt103 .PodaciOUplati.Iznos();
    }

}
