spring:
    datasource:
        url: jdbc:mysql://localhost:3306/quatrofantasticoxmlcompany2?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: init2.sql

environment:
    pib: 22222222222
