spring:
    datasource:
        url: jdbc:mysql://localhost:3306/quatrofantasticoxmlcompany1?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: root

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                    import_files: init1.sql

environment:
    pib: 11111111111
    bankUrl: http://localhost:8092/ws
