//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 02:05:30 PM CEST 
//


package com.ftn.model.dto.types;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TPodaciOPrenosu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPodaciOPrenosu"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="duznik_u_prenosu" type="{http://www.ftn.uns.ac.rs/tipovi}TPrenosUcesnik"/&gt;
 *         &lt;element name="poverilac_u_prenosu" type="{http://www.ftn.uns.ac.rs/tipovi}TPrenosUcesnik"/&gt;
 *         &lt;element name="iznos"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.ftn.uns.ac.rs/tipovi}TIznos"&gt;
 *               &lt;totalDigits value="15"/&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="oznaka_valute" type="{http://www.ftn.uns.ac.rs/tipovi}TOznakaValute" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPodaciOPrenosu", propOrder = {

})
public class TPodaciOPrenosu {

    @XmlElement(name = "duznik_u_prenosu", required = true)
    protected TPrenosUcesnik duznikUPrenosu;
    @XmlElement(name = "poverilac_u_prenosu", required = true)
    protected TPrenosUcesnik poverilacUPrenosu;
    @XmlElement(required = true)
    protected BigDecimal iznos;
    @XmlAttribute(name = "oznaka_valute")
    protected TOznakaValute oznakaValute;

    /**
     * Gets the value of the duznikUPrenosu property.
     * 
     * @return
     *     possible object is
     *     {@link TPrenosUcesnik }
     *     
     */
    public TPrenosUcesnik getDuznikUPrenosu() {
        return duznikUPrenosu;
    }

    /**
     * Sets the value of the duznikUPrenosu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrenosUcesnik }
     *     
     */
    public void setDuznikUPrenosu(TPrenosUcesnik value) {
        this.duznikUPrenosu = value;
    }

    /**
     * Gets the value of the poverilacUPrenosu property.
     * 
     * @return
     *     possible object is
     *     {@link TPrenosUcesnik }
     *     
     */
    public TPrenosUcesnik getPoverilacUPrenosu() {
        return poverilacUPrenosu;
    }

    /**
     * Sets the value of the poverilacUPrenosu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPrenosUcesnik }
     *     
     */
    public void setPoverilacUPrenosu(TPrenosUcesnik value) {
        this.poverilacUPrenosu = value;
    }

    /**
     * Gets the value of the iznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznos() {
        return iznos;
    }

    /**
     * Sets the value of the iznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznos(BigDecimal value) {
        this.iznos = value;
    }

    /**
     * Gets the value of the oznakaValute property.
     * 
     * @return
     *     possible object is
     *     {@link TOznakaValute }
     *     
     */
    public TOznakaValute getOznakaValute() {
        return oznakaValute;
    }

    /**
     * Sets the value of the oznakaValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOznakaValute }
     *     
     */
    public void setOznakaValute(TOznakaValute value) {
        this.oznakaValute = value;
    }

}
